service: jsonnodes
frameworkVersion: "3"
useDotenv: true

provider:
   name: aws
   runtime: nodejs16.x
   stage: dev
   region: ap-south-1
   timeout: 10

functions:
   hello:
      handler: src/server.handler
      events:
         - http: ANY /{proxy+}
         - http: ANY /

      environment:
         SECRET: ${env:SECRET}
         DATABASE_URL: ${env:DATABASE_URL}

plugins:
   - serverless-plugin-typescript
   - serverless-plugin-monorepo
